config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :folders do
    resources :memos
  end

  resources :mission
  root to: 'folders#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/folder.rb
class Folder < ApplicationRecord
  belongs_to :user
  has_many :memos
end

app/models/memo.rb
class Memo < ApplicationRecord
  belongs_to :folder, optional: true
end

app/models/mission.rb
class Mission < ApplicationRecord
  has_many :user_missions
  has_many :users, through: :user_missions
end

app/models/title.rb
class Title < ApplicationRecord
  has_many :user_titles
  has_many :users, through: :user_titles
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  
  has_many :folders
  has_many :memos, through: :folders

  has_many :user_missions
  has_many :missions, through: :user_missions

  # 新規登録時にデフォルトランクを設定
  before_create :set_default_rank

  def check_mission
    #nilの場合は0にする
    self.points ||= 0

    # 初めてのメモ作成時にポイントを追加
    if self.memos.count == 1
      mission_one_points = Mission.find_by(id: 3).points_value
      self.points += mission_one_points
    end

    # メモ作成回数が100回に達した時にポイントを追加
    if self.memos.count == 3
      mission_two_points = Mission.find_by(id: 4).points_value
      self.points += mission_two_points
    end

    # ポイントの変更があった場合のみ保存
    self.save if self.points_changed?
  end

  private
  
  def set_default_rank
    self.rank = '一般人' unless self.rank
  end


end

app/models/user_mission.rb
class UserMission < ApplicationRecord
  belongs_to :user
  belongs_to :mission
end

app/models/user_title.rb
class UserTitle < ApplicationRecord
  belongs_to :user
  belongs_to :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_action :set_folder, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /folders
  def index
    @folders = current_user.folders
    @folder = Folder.new  # 新しいフォルダ用
  end

  # GET /folders/1
  def show
  end

  # GET /folders/new
  def new
    @folder = Folder.new
  end

  # GET /folders/1/edit
  def edit
  end

  # POST /folders
  def create
    #ユーザーと関連づいたフォルダに変更しないとエラーとなる
    @folder = current_user.folders.new(folder_params) # 新しいフォルダ用

    if @folder.save
      redirect_to folders_path, notice: 'Folder was successfully created.'
    else
      @folders = Folder.all  # フォルダ一覧を再取得
      render :index
    end
  end

  # PATCH/PUT /folders/1
  def update
    if @folder.update(folder_params)
      redirect_to @folder, notice: 'Folder was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /folders/1
  def destroy
    @folder.destroy
    redirect_to folders_url, notice: 'Folder was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_folder
      @folder = Folder.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def folder_params
      params.require(:folder).permit(:name)
    end
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def index
  end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :set_folder
  before_action :set_memo, only: [:show, :edit, :update, :destroy]

  def index
    @memos = @folder.memos
  end

  def new
    @memo = @folder.memos.build
  end

  # GET /memos/1 or /memos/1.json
  def show
  end

  # GET /memos/1/edit
  def edit
  end

  def create
    # タイトルが空白の場合、自動的に「無題」を設定
    params[:memo][:title] = '無題' if params[:memo][:title].blank?
    @memo = @folder.memos.build(memo_params)

    if @memo.save
      current_user.check_mission
      
      redirect_to folder_memos_path(@folder), notice: 'Memo was successfully created.'
    else
      render :new
    end
  end

  def update
    @memo = Memo.find(params[:id])
  
    if @memo.update(memo_params)
      render json: { success: true }
    else
      render json: { success: false, error: @memo.errors.full_messages.to_sentence }
    end
  end

  # DELETE /memos/1 or /memos/1.json
  def destroy
    @memo.destroy
  
    respond_to do |format|
      format.html { redirect_to folder_memos_path(@folder), notice: "Memo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def set_folder
      @folder = Folder.find(params[:folder_id])
    end


    def set_memo
      @memo = @folder.memos.find(params[:id])
    end

    def memo_params
      params.require(:memo).permit(:title, :content)
    end
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/helpers/hello_codespaces_helper.rb
module HelloCodespacesHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/missions_helper.rb
module MissionsHelper
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/views/folders/_form.html.erb
<%= form_with(model: folder, local: true) do |form| %>
  <% if folder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(folder.errors.count, "error") %> prohibited this folder from being saved:</h2>

      <ul>
        <% folder.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :folder_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/folders/index.html.erb
<h1>Folders</h1>

<%= form_with(model: @folder, local: true) do |form| %>
  <% if @folder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@folder.errors.count, "error") %> prohibited this folder from being saved:</h2>

      <ul>
      <% @folder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit "Create Folder" %>
  </div>
<% end %>

<h2>Existing Folders</h2>

<ul>
  <% @folders.each do |folder| %>
    <li>
      <%= folder.name %>
      <%# ページ一覧へ %>
      <%# link_to 'Create Memo', new_folder_memo_path(folder) %>
      <%= link_to 'Show', folder_memos_path(folder) %>
    </li>
  <% end %>
</ul>

app/views/hello/index.html.erb
<div class="codespaces">
  <header class="codespaces-header">
    <img class="codespaces-logo"
         src="railstutorial.png"
         alt="Railsチュートリアル" />
    <p>
      Codespaces
      <span class="heart">♥️</span>
      Railsチュートリアル
    </p>
    <p class="small">
      🎓✨<br>
      ロゴ画像が表示されたらセットアップ完了です!
    </p>
  </header>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sample App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <!-- オーバーレイ -->
    <div id="overlay" style="display: none;"></div>

    <%= yield %>
  </body>
</html>

app/views/memos/_form.html.erb
<div class="container-fluid vh-100">
  <div class="row h-100">
    <!-- ナビゲーションパーシャルを読み込む -->
    <%= render 'shared/navbar' %>

    <!-- フォームをナビゲーションの右側に配置 -->
    <div class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
      <%= form_with(model: [@folder, memo], local: true, class: 'needs-validation', novalidate: true) do |form| %>
        <% if memo.errors.any? %>
          <!-- エラーメッセージをBootstrapのアラートスタイルで表示 -->
          <div class="alert alert-danger" role="alert">
            <h4 class="alert-heading"><%= pluralize(memo.errors.count, "error") %> prohibited this memo from being saved:</h4>
            <ul>
              <% memo.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <!-- Bootstrapのフォームグループを適用 -->
        <div class="mb-3">
          <%= form.label :title, class: 'form-label' %>
          <%= form.text_field :title, class: 'form-control' %>
        </div>

        <div class="mb-3">
          <%= form.label :content, class: 'form-label' %>
          <%= form.text_area :content, id: 'memo_content', class: 'form-control custom-textarea', style: 'height: 60vh;' %>
        </div>

        <!-- Bootstrapのボタンスタイルを適用 -->
        <div class="actions">
          <%= form.submit class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%# テンプレートモーダル用 %>
<div class="modal fade" id="templateModal" tabindex="-1" aria-labelledby="templateModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="templateModalLabel">テンプレート選択</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= button_tag '白紙にする', type: 'button', id: 'clear_textarea', class: 'btn btn-secondary', data: { template_type: 'clear_textarea' } %>
        <%= button_tag '貼り付け用テンプレート', type: 'button', id: 'insert_text2', class: 'btn btn-secondary', data: { template_type: 'insert_text2' } %>
        <%= button_tag 'エラー用テンプレート', type: 'button', id: 'insert_text3', class: 'btn btn-secondary', data: { template_type: 'insert_text3' } %>
      </div>
    </div>
  </div>
</div>

app/views/memos/_memo.html.erb
<div id="<%= dom_id memo %>">
  <p>
    <strong>Title:</strong>
    <%= memo.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= memo.content %>
  </p>

</div>

app/views/memos/edit.html.erb
<%= render 'form', memo: @memo %>

<%= link_to 'Back to Memos', folder_memos_path(@folder) %>

app/views/memos/index.html.erb
<div class="container-fluid vh-100">
  <div class="row h-100">
    
    <!-- ナビゲーションパーシャルを読み込む -->
    <%= render 'shared/navbar' %>
    <%= render 'shared/mypage' %>
    <%= render 'shared/contextMenu' %>

    <!-- メモ一覧 -->
    <main class="col-md-10 bg-light p-4">
      <h1 class="mb-4"><%= @folder.name %>のメモ</h1>

      <!-- マイページのポップアップコンテンツ -->
      <div id="mypage-popup" style="display: none;">
        <p>メールアドレス: <%= current_user.email %></p>
      </div>

      <%= link_to '新しいメモ', new_folder_memo_path(@folder), class: 'btn btn-primary mb-3' %>

      <div class="list-group" data-folder-id="<%= @folder.id %>">
        <% @memos.each do |memo| %>
            <div class="list-group-item d-flex justify-content-between align-items-center p-3" data-memo-id="<%= memo.id %>">
              <span class="memo-title"><%= memo.title %></span>
            <div>
              <%= link_to '表示', folder_memo_path(@folder, memo), class: 'btn btn-secondary btn-sm mx-1' %>
              <%= link_to '編集', edit_folder_memo_path(@folder, memo), class: 'btn btn-warning btn-sm mx-1' %>
              <%= link_to '削除', folder_memo_path(@folder, memo), data: {turbo_method: "delete", turbo_confirm: "削除してよろしいですか？"}, class: 'btn btn-danger btn-sm mx-1' %>
            </div>
          </div>
        <% end %>
      </div>

      <%= link_to 'フォルダーに戻る', folders_path, class: 'btn btn-light mt-3' %>
    </main>
  </div>
</div>



<%= form_with(url: folder_memo_path(@folder, 0), method: :patch, id: "rename-form", local: true) do |form| %>
  <div id="renamePopup" class="rename-popup" style="display: none;">
    <div class="rename-popup-content">
      <h3>メモの名前を変更</h3>
      <%= form.text_field :title, id: "newMemoName", class: "form-control" %>
      <%= form.submit "保存", id: "saveMemoName",class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/memos/new.html.erb
<%= render 'form', memo: @memo %>

<%= link_to 'Back to Folder', folder_memos_path(@folder) %>

app/views/shared/_contextMenu.html.erb
<div id="custom-context-menu" class="d-none">
  <%= link_to '削除', '#', data: { turbo_method: "delete", turbo_confirm: "本当に削除しますか？" }, id: "delete-memo", class: 'dropdown-item' %>
  <%= link_to '名前の変更', '#', id: "rename-memo", class: 'dropdown-item' %>
</div>



<%# link_to '削除', folder_memo_path(@folder, memo), data: {turbo_method: "delete", turbo_confirm: "削除してよろしいですか？"}  %>
<%# この形だと@folderとmemoの番号がわからないため削除時にどのメモを削除するかの情報がないためサーバーエラーとなる %>

app/views/shared/_mypage.html.erb
<div class="mypage-popup" id="mypage-popup" style="display: none;">
  <div class="card mb-3">
    <div class="card-header">
      プロフィール
    </div>
    <div class="card-body">
      <h5 class="card-title">
        <p><%= current_user.email %></p>
        <p>現在のランク：<%= current_user.rank %></p>
        <p>現在のポイント:<%= current_user.points %></p>
      </h5>
    </div>
  </div>

  <div class="card mb-3">
    <div class="card-header">
      アカウント情報
    </div>
    <div class="card-body">
      <h5 class="card-title">メールアドレス</h5>
      <p class="card-text"><%= current_user.email %></p>
      <div class="account-options">
        <p><%= link_to 'パスワードの変更', edit_user_registration_path %></p>
        <p><%= link_to "アカウント削除", registration_path(:user), data: { turbo_method: :delete }, style: "color: red;" %></p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="col-md-2 d-none d-md-block bg-dark sidebar h-100">
  <div class="position-sticky pt-3 h-100">
    <!-- ログインしているユーザーのメールアドレスを表示 -->
    <% if user_signed_in? %>
      <div class="px-3 text-white">
        <p><%= current_user.email %></p>
      </div>
    <% end %>

    <ul class="nav flex-column text-white">
      <li class="nav-item">
        <button id="mypage-link" class="btn btn-link text-decoration-none">マイページ</button>
      </li>
      <li class="nav-item">
        <%= link_to 'ホーム', root_path, class: 'nav-link text-white' %>
      </li>
      <li class="nav-item">
        <%= link_to 'フォルダー一覧', folders_path, class: 'nav-link text-white' %>
      </li>
      <li class="nav-item">
        <%= link_to '新しいメモ', new_folder_memo_path(@folder), class: 'nav-link text-white' %>
      </li>

      <%# メモの新規作成、編集ページ内のみ表示する %>
      <% if controller_name == 'memos' && (action_name == 'new' || action_name == 'edit') %>
        <li class="nav-item">
          <%= link_to 'テンプレート', '#', id: 'template-link', class: 'text-white', data: { bs_toggle: 'modal', bs_target: '#templateModal' } %>
        </li>
      <% end %>

      <li class="nav-item">
        <%= link_to 'ログアウト', destroy_user_session_path,  data: { turbo_method: :delete }, class: 'nav-link text-white' %>
      </li>
    </ul>
  </div>
</nav>